/**
 * ============================================================================
 * Interview Model - Smart Learning & Placement Preparation Portal
 * ============================================================================
 *
 * This model stores AI-generated mock interview questions for students.
 * The Gemini AI generates interview questions based on:
 *   - Selected topic (e.g., JavaScript, System Design, DBMS)
 *   - Chosen difficulty level
 *
 * Each interview session contains multiple questions with:
 *   - The interview question itself
 *   - An expected/model answer
 *   - Tips for answering effectively
 *   - Category classification for the question
 *
 * @module models/Interview
 * @requires mongoose
 */

const mongoose = require('mongoose');

/**
 * Sub-schema for individual interview questions.
 * Each question is generated by AI and contains guidance for the student.
 *
 * @typedef {Object} InterviewQuestionSchema
 * @property {String} question - The interview question text
 * @property {String} expectedAnswer - Model answer or key points to cover
 * @property {String} tips - Tips for answering this question effectively
 * @property {String} category - Category of the question (e.g., technical, behavioral)
 */
const interviewQuestionSchema = new mongoose.Schema(
  {
    /**
     * The interview question text as generated by AI.
     * Example: "Explain the difference between let, const, and var in JavaScript."
     */
    question: {
      type: String,
      trim: true,
    },

    /**
     * Model answer or key points that should be covered in the response.
     * This serves as a reference for the student to compare their answer.
     * Generated by Gemini AI based on best practices and common expectations.
     */
    expectedAnswer: {
      type: String,
      trim: true,
    },

    /**
     * Practical tips for answering this specific question effectively.
     * Example: "Start with a brief definition, then provide code examples."
     * Helps students improve their interview communication skills.
     */
    tips: {
      type: String,
      trim: true,
    },

    /**
     * Category of the interview question for organization.
     * Example: "technical", "behavioral", "situational", "coding"
     * Helps students focus on specific question types.
     */
    category: {
      type: String,
      trim: true,
    },
  },
  {
    _id: false, // No separate _id for question sub-documents
  }
);

/**
 * Main Interview Schema.
 *
 * @typedef {Object} InterviewSchema
 * @property {ObjectId} user - Reference to the student who requested the interview (required)
 * @property {String} topic - The interview topic selected by the student (required)
 * @property {String} difficulty - Difficulty level: easy, medium, or hard
 * @property {Array<InterviewQuestionSchema>} questions - AI-generated interview questions
 * @property {Date} generatedAt - When the interview questions were generated
 */
const interviewSchema = new mongoose.Schema(
  {
    // ── User Reference ──────────────────────────────────────────────

    /**
     * Reference to the User who requested this mock interview.
     * Each interview session is tied to a specific student.
     */
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',       // Reference to the User model
      required: [true, 'User reference is required'],
    },

    // ── Interview Configuration ─────────────────────────────────────

    /**
     * Topic/subject area for the interview questions.
     * The student selects this before generating questions.
     * Examples: "JavaScript", "React", "System Design", "DBMS",
     *           "Operating Systems", "Computer Networks"
     */
    topic: {
      type: String,
      required: [true, 'Interview topic is required'],
      trim: true,
    },

    /**
     * Difficulty level for the generated questions.
     * Controls the complexity and depth of questions:
     *   - 'easy': Basic concepts, definitions, simple explanations
     *   - 'medium': Application-level, comparisons, moderate complexity
     *   - 'hard': Advanced concepts, system design, optimization, edge cases
     */
    difficulty: {
      type: String,
      enum: {
        values: ['easy', 'medium', 'hard'],
        message: 'Difficulty must be easy, medium, or hard',
      },
      default: 'medium',
    },

    // ── Generated Questions ─────────────────────────────────────────

    /**
     * Array of interview question sub-documents generated by Gemini AI.
     * Typically contains 5-10 questions per session, depending on
     * the topic and difficulty level.
     */
    questions: [interviewQuestionSchema],

    // ── Metadata ────────────────────────────────────────────────────

    /**
     * Timestamp when the AI generated these interview questions.
     * Defaults to the current time at document creation.
     * Useful for tracking how recently the student practiced.
     */
    generatedAt: {
      type: Date,
      default: Date.now,
    },
  }
);

// ── Create and Export the Model ─────────────────────────────────────────
/**
 * Create the Interview model from the schema.
 * MongoDB will create an 'interviews' collection (lowercase, pluralized).
 */
const Interview = mongoose.model('Interview', interviewSchema);

module.exports = Interview;
